version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum ".circleci/environment.yml" }}
      - run:
          name: Install dependencies (if needed)
          command: |
            conda env list | grep anaconda-docker >/dev/null
            if [[ $? != 0 ]]; then
                conda env create -f .circleci/environment.yml
            fi
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum ".circleci/environment.yml" }}
          paths:
            - "/opt/conda"
      - run: 
          name: Run unit tests
          command: conda run -n anaconda-docker python -m unittest discover -v

    